title: Susan Christine Massey | DrMathy
baseurl: /drmathy
url: http://scmassey.github.io
markdown: kramdown
github_username: scmassey
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
collections:
  - sections
